IGVF-DACC/igvf-ui

pages/awards/[name].js
Make non-required property display conditional.
=> IGVF-56 Further award updates

components/collection.js, components/data-item.js, components/page-preamble.js, components/page-title.js, pages/_document.js, pages/awards/[name].js, pages/awards/index.js, pages/labs/[name].js, pages/labs/index.js, pages/users/[uuid].js, pages/users/index.js, styles/globals.css, tailwind.config.js
I also updated the Tailwind styles for more consistency.
=> IGVF-57 Improve the lab collection

components/navigation.js
Once dealing with real objects, I found Auth0 and the server getting out of sync as to whether the user had authenticated or not. This happened because I had ignored the `isLoading` status from `useAuth0()`, which meant I could treat `isAuthenticated===false` as the final state even when the user had authenticated with Auth0, causing me to log them out of the server.
=> IGVF-62 Synchronize authenticating with Auth0 and the server better

components/icon.js, components/navigation.js, components/no-collection-data.js, libs/__tests__/request.test.js, libs/authentication.js, libs/breadcrumbs.js, libs/request.js, pages/auth-error.js, pages/awards/[name].js, pages/awards/index.js, pages/labs/[name].js, pages/labs/index.js, pages/technical_samples/[uuid].js, pages/technical_samples/index.js, pages/users/[uuid].js, pages/users/index.js
This branch also allows you to view non-released data while you have signed in.
=> IGVF-94 Add technical sample collection and individual pages

libs/constants.js, pages/treatments/[uuid].js
Updated to use the new temperature properties.
=> IGVF-149-treatment-temperature

components/collection.js
=> IGVF-211 Remove propTypes warning with unknown collection types

.circleci/config.yml, cdk/infrastructure/config.py, components/navigation.js, cypress/integration/app.spec.js, libs/__tests__/breadcrumbs.test.js, libs/breadcrumbs.js, libs/request.js, package-lock.json, package.json, pages/_app.js, pages/profiles/[profile].js, pages/profiles/index.js
- Adds hierarchy view of schemas
- Displays schemas and changelogs
=> IGVF-145 display schemas and hierarchy

cdk/infrastructure/config.py, package-lock.json, pages/assay-terms/[name].js, pages/assay-terms/index.js, pages/phenotype-terms/[name].js, pages/phenotype-terms/index.js, pages/sample-terms/[name].js, pages/sample-terms/index.js
I changed the title of this ticket to include adding the Edit JSON button to the ontology term pages. I added those pages before editing was added but it didn’t get merged until after.
The changes only involve adding the editability wrapper around the term object pages, and the table-view wrappers around the term collection pages.
=> IGVF-236 Add editability and table views to term pages

cdk/infrastructure/config.py, components/no-content.js, cypress/e2e/app.cy.js, lib/__tests__/fetch-request.test.js, lib/fetch-request.js, package-lock.json, package.json, pages/[...path].js, pages/cell-lines/index.js, pages/genes/index.js, pages/users/[uuid].js, pages/users/index.js
I noticed I made a mistake with the NoCollectionData component, duplicating it in the no-content.js file. I’ve removed that duplication, and now everyone calls the one in the no-collection-data.js file.
=> IGVF-28 Implement a user collection page

components/common-data-items.js, components/instruction.js, package-lock.json
Since `biosample.embryonic` is valid and displayable, I had to check for the `embryonic` property’s existence using `in`.
=> IGVF-284 Change biosample display for schema update

components/add.js, components/button.js, components/edit-func.js, components/edit.js, lib/fetch-request.js, lib/general.js, lib/profiles.js, package-lock.json, package.json, pages/assay-terms/index.js, pages/awards/index.js, pages/cell-lines/index.js, pages/differentiated-cells/index.js, pages/differentiated-tissues/index.js, pages/documents/index.js, pages/genes/index.js, pages/human-donors/[uuid].js, pages/human-donors/index.js, pages/labs/index.js, pages/phenotype-terms/index.js, pages/primary-cells/index.js, pages/profiles/[profile].js, pages/profiles/index.js, pages/rodent-donors/index.js, pages/sample-terms/index.js, pages/technical-samples/index.js, pages/tissues/index.js, pages/treatments/index.js, pages/users/index.js
I had to create a new branch name in order to satisfy the demo gods (underscores not allowed in branch names). Since PRs don't know how to track changed branch names, here's a new PR with the same code. Here is the old PR: https://github.com/IGVF-DACC/igvf-ui/pull/82
=> Igvf-261-add-button (renamed branch)

components/__tests__/chromosome-locations.test.js, components/chromosome-locations.js, components/collection/__mocks__/profiles.js, components/collection/__tests__/.eslintrc.json, components/collection/__tests__/cell-renderers.test.js, components/collection/__tests__/generate-table-columns.test.js, components/collection/cell-renderers.js, components/collection/generate-table-columns.js, components/collection/table.js, lib/__tests__/collection-table.test.js, lib/__tests__/dates.test.js, lib/collection-table.js, lib/dates.js, package-lock.json, package.json, pages/genes/[id].js
I broke my own rule very badly in this branch. Many Jest tests now fail coveralls coverage because the amount of time it will take to fix all these at this stage would be prohibitive IMO. I would like to have IGVF-324 as a high priority, maybe before IGVF-318.
=> IGVF-309-table-cell-renders

components/add.js, components/button.js, components/edit-func.js, components/edit.js, components/link-icon.js, pages/profiles/[profile].js, pages/profiles/index.js
* Error messages use FlashMessage
* Server validation errors show up
* Edit/Add buttons are now Icons that also link
* Created the LinkIcon component which is both a Link button and an Icon button
* Placed the Save/Cancel to the right
* Add/Edit buttons now placed to the right
* The issue of signing in from sign-out not showing the button I was unable to reproduce
* Proper spacing between buttons and other UI elements
* Inactive state may or may not be better than before? Not sure
* Showing the title of the object currently being edited
* Cancel is now using a more distinct button type
=> Igvf 201 button UI

cdk/infrastructure/config.py, components/add.js, components/profile-map.js, docker-compose.prod-local.yml, docker-compose.test.yml, docker-compose.yml, jest.setup.js, lib/constants.js, lib/fetch-request.js, lib/profiles.js, next.config.js, pages/_app.js, pages/api/mapprofile.js, pages/profiles/[profile].js
* Pulls in @forresttanaka mapprofile nextjs api
* The mapprofile api will take a schema name and return the associated collection
* This collection is then used for the Add button logic
* Removed the hard coded mapping between schema and collection
=> IGVF-336-crashfix

components/attribution.js, components/breadcrumbs.js, components/collection/cell-renderers.js, components/common-data-items.js, components/item-link.js, components/logo.js, components/navigation.js, components/page-component/page-navigation.js, components/source-prop.js, components/treatment-table.js, cypress/e2e/page.cy.js, docker-compose.cypress-m1.yml, lib/__tests__/fetch-request.test.js, package-lock.json, package.json, pages/help.js, pages/labs/[name].js, pages/profiles/index.js, pages/technical-samples/[uuid].js, pages/users/[uuid].js, pages/users/index.js
* The `<Link>` component now doesn’t allow `<a>` elements as children without an optional flag. All `<Link>` components in this branch have had their `<a>` elements removed. See the [NextJS 13 note about the `<Link>` component changes](https://nextjs.org/docs/upgrading#link-component).
* I think I did something very odd with the main navigation in that I wrapped the buttons in a `<Link>` which seems to have served no purpose. I removed those `<Link>` components.
=> IGVF-335 Upgrade NextJS to version 13

components/navigation.js, components/search/list-renderer/index.js, cypress/e2e/app.cy.js, package-lock.json, pages/in-vitro-systems/[id].js
This mostly copies other biosample-derived pages such as Primary Cells, so the displays should appear basically the same.
=> IGVF-381 Add in vitro system object, list, and report pages

components/attribution.js, components/common-data-items.js, components/phenotypic-feature-table.js, components/search/__tests__/list-renderer.test.js, components/search/list-renderer/human-donor.js, package-lock.json, package.json, pages/human-donors/[uuid].js
preliminary adding phenotypic features, donor references, and url to human donor object pages. Start of adding human donor phenotypic features and collections to search result items
=> IGVF-435-reconcile-human-donor

components/search/__tests__/list-renderer.test.js, components/search/list-renderer/human-genomic-variant.js, components/search/list-renderer/index.js, pages/human-genomic-variants/[uuid].js
Human genomic variant object page and search result start
This PR on igvfd goes along with this: https://github.com/IGVF-DACC/igvfd/pull/276
=> IGVF-456-human-genomic-variant

components/common-data-items.js, pages/in-vitro-systems/[id].js, pages/primary-cells/[uuid].js, pages/tissues/[uuid].js, pages/whole-organisms/[id].js
=> IGVF-190-pooled-from

components/form-elements/button.js, components/search-results/download-tsv.js, components/search-results/header.js, components/search-results/items-per-page-selector.js, components/search-results/search-pager.js, cypress/e2e/add.cy.js, pages/report.js
Link and icon to download the currently viewed report as a TSV
=> IGVF-461-TSV-report-download

cdk/infrastructure/config.py, cypress/e2e/version.cy.js, lib/constants.js, next.config.js, package-lock.json, pages/help.js
The UI version now gets set manually in next.config.js, where the UI code can access it.
=> IGVF-416 UI version

cdk/infrastructure/config.py, components/edit.js, package-lock.json
I believe what happened is that the CSFR token created at the beginning of the edit process was getting stale after the page reload. I now create new FetchRequest objects with the new CSFR token just before each server operation.
=> IGVF-525 Fix generic errors when saving objects

components/phenotypic-feature-table.js, components/product-info.js, components/search/__tests__/list-renderer.test.js, components/search/list-renderer/rodent-donor.js, pages/human-donors/[uuid].js, pages/rodent-donors/[uuid].js
Rodent Donor search and object page
=> IGVF-445-reconcile-mouse-donor

components/__tests__/sortable-grid.test.js, components/sortable-grid.js, package-lock.json, pages/measurement-sets/[id].js
This is the same code Jennifer QAed, so if you pass this, I’ll just merge then.
=> IGVF-683 file table

components/dbxref-list.js
fixing CL and EFO linkout in dbxref list
=> IGVF-654-CL-linkout

components/access-keys.js, components/attachment-thumbnail.js, components/data-area.js, components/form-elements/select.js, components/navigation.js, components/search-results/count.js, components/search/list-renderer/index.js, components/search/list-renderer/modification.js, pages/modifications/[uuid].js, pages/profiles/graph.svg.js
This just adds the Modification Page and Search result list
=> Igvf-522-modification-page

next.config.js
updating to new major version (4.0.0) due to node version 18 update
=> update version v4.0

components/docs/sortable-grid.md, components/page-component/docs/page-navigation.md, docs/page-editors-guide.md
We won’t need a demo for this. Just need to make sure I updated not only the descriptions of anchor tags correctly, but also my use of them in other Markdown documents.
=> IGVF-691 Fix anchor tag documentation

cdk/infrastructure/config.py, components/id-search-trigger.js, components/navigation.js, components/search-modal.js, components/site-search-trigger.js, package-lock.json, pages/id-search.js
You’ll find a lot of deletions in site-search-trigger.js because I moved all the modal processing to the new search-modal.js file so that both the existing site search and this new identifier search can share it.
=> IGVF-731 Add identifier searches that go to specific object pages

pages/technical-samples/[uuid].js
source object is now included directly in the TechnicalSample props and loaded on the server
=> IGVF-738-sample-source

cdk/infrastructure/config.py, components/form-elements/button.js, components/icon.js, components/navigation.js, cypress/e2e/access-keys.cy.js, cypress/e2e/app.cy.js, cypress/e2e/authentication-redirect.cy.js, cypress/e2e/breadcrumbs.cy.js, cypress/e2e/documents.cy.js, cypress/e2e/edit.cy.js, cypress/e2e/facets.cy.js, cypress/e2e/help.cy.js, cypress/e2e/impersonate-user.cy.js, cypress/e2e/mobile-menu.cy.js, cypress/e2e/page-component.cy.js, cypress/e2e/page.cy.js, cypress/e2e/search.cy.js, cypress/e2e/version.cy.js, cypress/support/commands.js, pages/profiles/graph.svg.js
You’ll find most relevant changes in navigation.js and icon.js. Most other changes involve updating the Cypress tests for the new navigation arrangement, plus a couple of other small bug fixes. I removed the `label` from buttons because it had `aria-label`, so we were seeing a lot of duplicate text. This caused a lot of broken Cypress tests.
=> IGVF-534 Redesign the main navigation

components/docs/search-list-item-renderers.md, cypress/e2e/site-id-search.cy.js, lib/__tests__/report.test.js, lib/breadcrumbs.js, pages/impersonate-user.js, pages/site-search.js
updating site-search page to use the backend `query` parameter instead of `searchTerm`
=> IGVF-715-use-query

components/search/list-renderer/index.js
=> Revert "IGVF-831 Fix crash in list renderer for unknown types"

components/__tests__/ontology.test.js, components/alias-list.js, components/search/__tests__/list-renderer.test.js, components/search/list-renderer/index.js, components/search/list-renderer/model.js, lib/curie.js, package-lock.json, package.json, pages/models/[id].js
Mostly pretty standard, but I did change curie.js to allow colons in the path portion, because some test data has that.
=> IGVF-786 Add Model search-list and object pages

components/search/__tests__/list-renderer.test.js, components/search/list-renderer/biomarker.js, lib/biomarker.js
Added a few property to the biomarker page.
=> IGVF-805-ui-biomarker-page

pages/human-donors/[uuid].js
Just adds a data item label and value for human donor identifier
=> IGVF-745-human-donor-identifier

components/search/__tests__/list-renderer.test.js, components/search/__tests__/search-list-renderer.test.js, components/search/list-renderer/analysis-set.js, package-lock.json, package.json, pages/analysis-sets/[id].js, pages/models/[id].js
[IGVF-882](https://igvf.atlassian.net/browse/IGVF-882) embeds their `input_file_sets` properties, so we no longer need to request them for their object pages, nor for the AnalysisSet search-list page (Model search-list results never displayed `input_file_sets`).
[IGVF-882]: https://igvf.atlassian.net/browse/IGVF-882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IGVF-920 Update AnalysisSet and Model for embedded input_file_sets

components/__mocks__/profile.js, components/__tests__/data-area.test.js, components/data-area.js, components/search/__tests__/list-renderer.test.js, components/search/list-renderer/construct-library.js, components/search/list-renderer/index.js, components/sequencing-file-table.js, lib/common-requests.js, package-lock.json, package.json, pages/construct-libraries/[id].js, pages/measurement-sets/[id].js
Most of this PR isn’t novel, but builds on what we already have. But one novel piece involves the collapsable data item values. You get a button that lets the user expand and collapse data areas that might get large. We can use this for existing properties too, but I only used it on ConstructLibrary objects for now, where the ticket specified.
I extracted the MeasurementSet sequencing file table to its own module, so ConstructLibrary can share it.
=> IGVF-812 Construct library object and search pages

components/file-set-table.js, components/search/list-renderer/auxiliary-set.js, components/search/list-renderer/index.js, components/sequencing-file-table.js, lib/__tests__/files.test.ts, lib/common-requests.js, lib/files.ts, package-lock.json, pages/auxiliary-sets/[id].js, pages/measurement-sets/[id].js, tsconfig.json
Pretty standard stuff, though I did make a new FileSet table component and a new lib/files.ts file for generic file utilities.
=> IGVF-832 AuxiliarySet object and search pages

components/__tests__/data-area.test.js, components/common-data-items.js, components/data-area.js, package-lock.json, pages/awards/[name].js, pages/documents/[id].js, pages/labs/[name].js, pages/reference-files/[...id].js, pages/software/[id].js
I decided to also fix the `rel` property on external links which should have both **noopener** and **noreferrer**, and I often only added the latter.
I also found some cases of external links using the `<Link>` component, so I changed those to `<a>` elements.
=> IGVF-688 Fix URL text wrapping

components/facets/custom-facets/standard-terms.js
fixing StandardTerms component to remove 'from' from query string when a facet changes.
Tests are incoming
=> IGVF-750-facet-selections

package-lock.json, package.json, pages/profiles/graph.svg.js
* using ReactSVGPanZoom to display the large schema digram
=> IGVF-858-schema-diagram

.eslintrc.json, lib/__tests__/result.test.ts, lib/result.ts
Result type and small eslint update for unused variables
=> IGVF-1095-result-type

components/__tests__/checkbox.test.js, components/__tests__/long-click.test.js, components/checkbox.js, components/facets/__tests__/facet-groups.test.js, components/facets/__tests__/facet-section.test.js, components/facets/__tests__/facet-tags.test.js, components/facets/__tests__/facet-term.test.js, components/facets/__tests__/facet.test.js, components/facets/custom-facets/docs/custom-facets.md, components/facets/custom-facets/standard-tag-label.js, components/facets/custom-facets/standard-term-label.js, components/facets/custom-facets/standard-terms.js, components/facets/custom-facets/taxa-tag-label.js, components/facets/custom-facets/taxa-term-label.js, components/facets/facet-groups.js, components/facets/facet-registry.js, components/facets/facet-section.js, components/facets/facet-tags.js, components/facets/facet-term.js, components/facets/facet.js, components/help-tip.js, components/long-click.js, components/report/column-selector.js, cypress/e2e/facets.cy.js, lib/__tests__/facets.test.js, lib/facets.js, package-lock.json, package.json, styles/globals.css, tailwind.config.js
* Update npm packages.
* Prepare for handling buttons in the title.
* Make the wildcard buttons fully functional. Have selections of regular terms remove wildcard selections.
* Update package-lock.json after rebase to dev.
* Add custom facet element for tag labels. Add a standard tag-label as well as one for taxa.
* Implement select-all and select-none buttons.
* Add Clear All button to search results.
* Make new selection controls accessible.
* Full Jest test coverage.
* Update the facet documentation to include the custom facet tag labels.
* Remove a console.log.
=> IGVF-1017 Allow group and wildcard facet selections

components/__tests__/file-download.test.js, components/file-download.js, components/file-table.js, components/report/cell-renderers.js, components/sequencing-file-table.js, package-lock.json, pages/analysis-sets/[id].js, pages/auxiliary-sets/[id].js, pages/configuration-files/[...id].js, pages/construct-library-sets/[id].js, pages/curated-sets/[id].js, pages/measurement-sets/[id].js, pages/model-sets/[id].js, pages/prediction-sets/[id].js
In `FileDownload` I removed the `API_URL` to get new Jest tests to work correctly. The chances of `API_URL` being undefined seems remote, and the consequences of enabling the button while `API_URL` is undefined seems small.
=> IGVF-1187 Add report view button for files within a file-set

cdk/infrastructure/config.py, components/form-elements/index.js, lib/fetch-request.ts, next.config.js, package-lock.json, pages/[...path].js
In this case I pointed the demo at the igvfd dev demo just because I know we don’t need to modify the database for QA, so might as well save the $20 or whatever it is spinning up an igvfd demo.
=> IGVF-986 Have unhandled igvfd endpoints 404 in UI

cypress.config.js, cypress/e2e/access-keys.cy.js, cypress/e2e/page.cy.js, cypress/support/commands.js, docker-compose.cypress-m1.yml, docker/cypress/cypress-docker.config.js, docker/cypress/docker-compose.cypress-on-circle.yml, package-lock.json, package.json
This has to work locally, locally in docker, and on CircleCI.
=> IGVF-1229 Upgrade to Cypress version 13

cypress/e2e/app.cy.js, lib/search-results.js, package-lock.json, package.json, pages/multireport.js, pages/profiles/[profile].js, pages/search.js, tsconfig.json
In addition, I changed the mechanism to display titles for search, report, and schema pages to be consistent with the titles on the schemas page.
=> IGVF-1204 Cypress test for all list and report pages

cypress/e2e/edit.cy.js, cypress/e2e/page-component.cy.js, cypress/e2e/page.cy.js
* I added a test for the CHEVRON_NAV page component that I’d forgotten to add.
* I unchained some items in edit.cy.js that were causing ESLint errors.
* I changed the page tests that modified pages to create a page and then modify it. I also removed a test I felt was redundant.
=> IGVF-1245 Make Cypress page tests idempotent

components/report/__tests__/cell-renderers.test.js, components/report/cell-renderers.js
What I did in this ticket is to display full URL or a list of full URL for attachment.href and files.href.
=> IGVF-1262-report-href

cdk/infrastructure/config.py, components/navigation.js, package-lock.json, package.json
Looks to me like it looks fine to remove the line completely on all pages.
=> IGVF-909 Remove navigation vertical border

components/common-data-items.js, cypress.config.js, lib/common-requests.ts, pages/in-vitro-systems/[id].js, pages/measurement-sets/[id].js, pages/multiplexed-samples/[uuid].js, pages/prediction-sets/[id].js, pages/primary-cells/[uuid].js, pages/technical-samples/[uuid].js, pages/tissues/[uuid].js, pages/whole-organisms/[id].js
adding construct library sets to multiplexed samples, prediction sets, and measurement sets
=> IGVF-1079-construct-library-summary

cdk/README.md, docker/nextjs/Dockerfile, package-lock.json
Running locally and deploying a demo worked fine for me while running node 20.10.0 locally.
=> IGVF-1368 Upgrade igvf-ui to node 20

package-lock.json, pages/analysis-sets/[id].js
`submitter_comment` isn’t a required property, but appears on other file-set pages, so I added that to this page too.
=> IGVF-1466 Fix analysis-set pages to display at least minimal properties

cdk/infrastructure/config.py, components/__tests__/status.test.js, components/alias-list.js, components/docs/sortable-grid.md, components/status.js, lib/common-requests.ts, pages/analysis-sets/[id].js
As with ENCODE, I’ve added icons to the status badges. This lets me have the icon-only status badges (I call them “abbreviated status” in the code with tooltips indicating the status.
=> IGVF-1532 New analysis set summary page tables

cypress/e2e/facets.cy.js
Update facet test for the new InVitroSystem test data insert.
=> IGVF-1576 Update facet Cypress test

components/__tests__/audit.test.js, components/audit.js, components/facets/custom-facets/audit-title.js, cypress/e2e/audit.cy.js, lib/audit.ts, styles/globals.css, tailwind.config.js
One potentially confusing part about this my removal of the audit icon background components I used for the audit facets. I’ve integrated these backgrounds into the base icons themselves so they all have backgrounds instead of just the facet audit icons.
=> IGVF-1386 Redesign audits

components/linked-id-and-status-stack.js, package-lock.json, package.json, pages/analysis-sets/[id].js
This mostly involved just adding a little margin, but I made a new component so all these stacks look the same.
=> IGVF-1612 Fix stacked linked accessions and statuses

pages/measurement-sets/[id].js
This also fixes a bug where the Library Construction Platform doesn’t get displayed, probably because of an embedding change.
=> IGVF-1642 Display sequencing library types on measurement set summary pages

components/analysis-step-table.js, components/common-data-items.js, components/donor-table.js, components/file-table.js, components/linked-id-and-status.js, components/sample-table.js, lib/common-requests.ts, pages/analysis-sets/[id].js, pages/auxiliary-sets/[id].js, pages/construct-library-sets/[id].js, pages/curated-sets/[id].js, pages/in-vitro-systems/[id].js, pages/matrix-files/[...id].js, pages/measurement-sets/[id].js, pages/model-sets/[id].js, pages/multiplexed-samples/[uuid].js, pages/prediction-sets/[id].js, pages/primary-cells/[uuid].js, pages/sequence-files/[...id].js, pages/signal-files/[...id].js, pages/technical-samples/[uuid].js, pages/tissues/[uuid].js, pages/whole-organisms/[id].js, pages/workflows/[id].js
While WholeOrganism has `partOf` and `pooledFrom` in its schema, you cannot include these properties in any submitted WholeOrganism object. I removed both these properties from the WholeOrganism page.
=> IGVF-1601 Change linked lists of accessions to tables

components/page.js, components/site-info.js, pages/help/about-igvf.js
This gives the database-driven page with the path /help/about-igvf special treatment so that it displays the version information and social links in a reasonably nice way IMO.
=> IGVF-1687 Return version and social link display

components/input-file-sets.js, components/navigation.js, components/sample-table.js, lib/common-requests.ts, pages/analysis-sets/[id].js
I added a fix for the dark-mode About navigation icon because I forgot about dark mode before.
=> IGVF-1672 Update file-set tables on AnalysisSet pages

components/page.js, package-lock.json, styles/globals.css, tailwind.config.js
This is for next week’s release, not today’s.
=> IGVF-1026 Make h2 top margins on pages consistent

cdk/infrastructure/config.py, components/input-file-sets.js, pages/analysis-sets/[id].js
I was filtering a list, then displaying the original unfiltered list.
=> IGVF-1716 AnalysisSet table associated file-sets fix

cdk/infrastructure/config.py, components/scroll-to-top.js, pages/_document.js, styles/globals.css
I recently heard that the popover API was made common among all major browsers, so I decided to use that here instead of another portal root element.
=> IGVF-1593 Fix scroll-to-top button

components/chart-file-set-lab.js, pages/content/fileset-chart.js
The large change is actually just an indenting change.
=> IGVF-1837 Filter embeddable file-set chart with query string

pages/_app.js
I included this ticket’s demo server in the list of servers to show the banner, but will delete that entry before merging.
=> IGVF-1841 Test data warning banner on staging and sandbox

components/common-data-items.js, components/software-table.js, components/software-version-table.js, components/workflow-table.js, lib/__tests__/common-requests.test.ts, lib/common-requests.ts, pages/analysis-sets/[id].js, pages/auxiliary-sets/[id].js, pages/construct-library-sets/[id].js, pages/curated-sets/[id].js, pages/human-donors/[uuid].js, pages/in-vitro-systems/[id].js, pages/measurement-sets/[id].js, pages/model-sets/[id].js, pages/multiplexed-samples/[uuid].js, pages/prediction-sets/[id].js, pages/primary-cells/[uuid].js, pages/publications/[id].js, pages/rodent-donors/[uuid].js, pages/software/[id].js, pages/technical-samples/[uuid].js, pages/tissues/[uuid].js, pages/whole-organisms/[id].js, pages/workflows/[id].js
Looks like a lot, but it mostly has the same or similar changes on every relevant page.
=> IGVF-1807 Display publication-page tables and links to publications

components/unknown-type-panel.js, components/unspecified-property.js
I’d forgotten that generic pages and report pages shared a bit of code.
=> IGVF-1895 Fix generic page crash

components/search-results/download-tsv.js, package-lock.json
Two buttons now, one or the other visible. There are other ways to do that, but two buttons here is so low cost, it’s much simpler.
=> IGVF-1891 Report-download button has text label

lib/breadcrumbs.ts, package-lock.json, package.json
I also updated npm package versions.
=> IGVF-1965 Trim codes from solo breadcrumb titles

components/facets/facet-groups.js
=> IGVF-1959 Make long facet group titles look better

components/session-context.js, lib/__mocks__/redis.ts, lib/__tests__/cache.test.ts, lib/cache-client.ts, lib/cache.ts, lib/collection-titles.ts, lib/docs/cache.md, lib/profiles.ts, lib/server-objects.ts, package-lock.json, pages/api/collection-titles.ts, pages/api/profiles.ts, pages/audits.js, pages/index.js, pages/profiles/index.js
This also introduces a new module to make using the Redis cache easy to use from anywhere in the NextJS code.
=> IGVF-2056 Cache common objects

components/input-file-sets.js, pages/model-sets/[id].js
Also fixed an ordering issue on the model-set pages.
=> IGVF-2124 Fix multiple collapsing input file set tables

components/navigation.js
Add navigation item for igvf-dacc GitHub issues.
=> IGVF-2169 Add navigation link to GitHub issues

components/input-file-sets.js, package-lock.json, pages/analysis-sets/[id].js, pages/in-vitro-systems/[id].js, pages/multiplexed-samples/[uuid].js, pages/primary-cells/[uuid].js, pages/technical-samples/[uuid].js, pages/tissues/[uuid].js, pages/whole-organisms/[id].js
I also updated npm package versions, but added no new ones.
=> IGVF-2325 Update construct library set and donor displays for new object embedding

cdk/infrastructure/config.py, components/data-table.tsx, components/navigation.js, components/static-table.tsx, lib/__tests__/data-table.test.ts, lib/data-table.ts, pages/cell-models/[view].tsx, pages/computational-tools.js, styles/globals.css, tailwind.config.ts
This is a weird one in that it has a static page that will likely go away in the coming months. It also has a data-table module that might go away, or it might become the standard way to display tables instead of the data-grid modules. But we need this in this week’s release and then we’ll figure out the path forward.
=> IGVF-2266 Computational Tools page

components/navigation.js, pages/predictive-models.tsx
Similar to the computational tools page, this page is static and does no database queries. We’ll probably replace it with a dynamic page once we have enough data.
=> IGVF-2267 Predictive model page

cdk/infrastructure/config.py, components/data-table.tsx, components/docs/data-table.md, components/facets/__tests__/standard-terms.test.js, components/navigation.js, lib/__tests__/data-table.test.ts, lib/data-table.ts, lib/matrix.ts, pages/assays.tsx, pages/tissue-summary/[taxa].tsx, styles/globals.css, tailwind.config.ts
Kind of large, but the important files are data-table.tsx, data-table.ts, and of course assays.tsx — the new page.
=> IGVF-2333 Assay table page

components/__tests__/controlled-access.test.tsx, components/__tests__/data-use-limitation-status.test.tsx, components/common-data-items.js, components/controlled-access.tsx, components/data-use-limitation-status.tsx, components/institutional-certificate-table.tsx, components/search/list-renderer/institutional-certificate.tsx, globals.d.ts, lib/__tests__/common-requests.test.ts, lib/__tests__/data-use-limitation.test.ts, lib/common-requests.ts, lib/data-use-limitation.ts, pages/alignment-files/[...id].js, pages/in-vitro-systems/[id].js, pages/index-files/[...id].tsx, pages/institutional-certificates/[...id].tsx, pages/model-files/[...id].js, pages/multiplexed-samples/[uuid].js, pages/primary-cells/[uuid].js, pages/reference-files/[...id].js, pages/sequence-files/[...id].js, pages/tabular-files/[...id].js, pages/technical-samples/[uuid].js, pages/tissues/[uuid].js, pages/whole-organisms/[id].js
The most important files are the new ones:
Controlled-access badge
`components/controlled-access.tsx`
Data-use-limitation badge
`components/data-use-limitation-status.tsx`
Table of institutional certificates
`components/institutional-certificate-table.tsx`
Utilities for data-use limitations
`lib/data-use-limitation.ts`
The rest are alterations to use these new files, and Jest tests.
=> IGVF-2448 Data-use-limitation badges

package-lock.json, package.json, pages/tabular-files/[...id].js
Also updated npm package versions. Updating @floating-ui/react causes a Jest test failure, though I haven’t investigated why yet.
=> IGVF-2550-barcode-map-report-link

components/id-search-trigger.js, components/site-search-trigger.js, lib/__tests__/special-search.test.ts, lib/special-search.ts
This is for next week, but I’m out Thursday and Friday so I wanted to make sure they’ll make it next week Tuesday.
=> IGVF-2582 Allow paths in site search

pages/analysis-steps/[id].js
Remove workflow display from analysis-step page.
=> IGVF-2736 Remove workflow from analysis-step pages

components/session-context.js, lib/__tests__/authentication.test.ts, lib/authentication.ts, lib/constants.ts, pages/_app.js
Also now putting the authentication state into browser local storage. Enabling that doesn't seem to cause any issues.
=> IGVF-2825 Authentication error page handling

pages/analysis-sets/[id].js
This branch adds support for displaying pipeline parameters and primer design files in the Analysis Set page. The implementation adds three new data categories: pipeline parameters documents, pipeline parameters tabular files, and primer design files.
- `pages/analysis-sets/[id].js` - Main analysis set page component
1. **Clean implementation**: The code follows existing patterns consistently throughout the file
2. **Proper data flow**: Server-side data fetching in `getServerSideProps` with correct prop passing to the component
3. **Logical data processing**: Pipeline parameters are appropriately grouped by type using lodash's `groupBy` function with the existing `pathToType` utility
4. **Robust error handling**: Uses optional chaining (`?.`) and proper length checks throughout
5. **Clear …
=> IGVF-2943 Add pipeline parameters and primer designs to analysis-set page

components/batch-download-fileset.tsx, components/batch-download.tsx, components/curated-set-file-table.js, components/file-set-files-tables.tsx, components/file-table.js, components/form-elements/button.js, components/sequencing-file-table.tsx, lib/__tests__/batch-download.test.ts, lib/__tests__/profiles.test.ts, lib/batch-download/base-controller.ts, lib/batch-download/file-table-controller.ts, lib/batch-download/fileset-controller.ts, lib/batch-download/index.ts, lib/batch-download/search-controller.ts, lib/profiles.ts, pages/analysis-sets/[id].js, pages/curated-sets/[id].js, pages/model-sets/[id].js, pages/prediction-sets/[id].js
This PR introduces a comprehensive batch download system refactor that adds new download options, improves type safety, and significantly enhances test coverage. **19 files changed** with **658 additions, 131 deletions**.
**File**: `components/batch-download-fileset.tsx` (164 lines added)
- ✅ **Excellent Implementation**: New React component for file-set specific downloads
- ✅ **Two Download Options**: Files only vs. files with inputs
- ✅ **Modern TypeScript**: Perfect const assertions and type derivation
- ✅ **Navigation Handling**: Smart state reset for SPA routing scenarios
- ✅ **Performance Optimized**: Proper `useMemo` usage with correct dependencies
**File**: `components/batch-download.tsx` (converted from .js)
- ✅ **TypeScript Migration**: Clean conversion with proper typing
- ✅ …
=> IGVF-2754 File and file-set batch-download update

components/common-data-items.js
This branch adds cell type annotation display functionality to the `FileDataItems` component, allowing users to view cell type information for files that have this annotation.
**File**: `components/common-data-items.js`
**Location**: Lines 625-635 (in `FileDataItems` component)
**Addition:**
```javascript
{item.cell_type_annotation && (
<>
<DataItemLabel>Cell Type Annotation</DataItemLabel>
<DataItemValue>
<Link href={item.cell_type_annotation["@id"]}>
{item.cell_type_annotation.term_name}
</Link>
</DataItemValue>
</>
)}
```
**Placement**: Between "Content Type" and "External Host URL" fields
1. **Consistent Pattern**: Follows the exact same conditional rendering pattern used throughout the component
2. **Proper Data Access**: Uses `item.cell_type_annotation["@id"]` and …
=> IGVF-2972 Show cell_type_annotation on file pages
